-- Esquema de Base de Datos EOFAP - @DMC.1NST1TUT3
-- Fecha: 2026-02-27

-- Estructura de tabla para TM_CONDICION
CREATE TABLE `TM_CONDICION` (
  `IDCONDICION` int NOT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDCONDICION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Estructura de tabla para TM_UBIGEO_FAP
CREATE TABLE `TM_UBIGEO_FAP` (
  `IDUBICACION` int NOT NULL,
  `LUGAR` varchar(500) DEFAULT NULL,
  `UBIGEO` int DEFAULT NULL,
  PRIMARY KEY (`IDUBICACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Estructura de tabla para TT_SITUACION
CREATE TABLE `TT_SITUACION` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FECHA` date DEFAULT NULL,
  `IDCONDICION` int DEFAULT NULL,
  `IDUBICACION` int DEFAULT NULL,
  `TOTALHORAS` decimal(10,2) DEFAULT NULL,
  `OBSERVACION` varchar(1000) DEFAULT NULL,
  `IDTIPOAERONAVE_EXT` int DEFAULT NULL,
  `TIPOAERONAVE` varchar(100) DEFAULT NULL,
  `MATRICULA` varchar(20) DEFAULT NULL,
  `CODUNIDAD` varchar(50) DEFAULT NULL,
  `SIGLA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TT_SITUACION_TM_CONDICION_FK` (`IDCONDICION`),
  KEY `TT_SITUACION_TM_UBIGEO_FAP_FK` (`IDUBICACION`),
  CONSTRAINT `TT_SITUACION_TM_CONDICION_FK` FOREIGN KEY (`IDCONDICION`) REFERENCES `TM_CONDICION` (`IDCONDICION`),
  CONSTRAINT `TT_SITUACION_TM_UBIGEO_FAP_FK` FOREIGN KEY (`IDUBICACION`) REFERENCES `TM_UBIGEO_FAP` (`IDUBICACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Estructura de tabla para TT_PARTE_DIARIO
CREATE TABLE `TT_PARTE_DIARIO` (
  `ID` int NOT NULL,
  `TIPOAERONAVE` varchar(100) DEFAULT NULL,
  `FECHAPARTE` date DEFAULT NULL,
  `IDTIPOAERONAVE_EXT` int DEFAULT NULL,
  `EFECTIVO` int DEFAULT NULL,
  `INOPERATIVOS` int DEFAULT NULL,
  `DISPONIBLES` int DEFAULT NULL,
  `OPERATIVOS` int DEFAULT NULL,
  `FECHACRE` date DEFAULT NULL,
  `USUARIOCRE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
